fix = true
exclude = [
    ".git",
    ".pre-commit-cache",
    ".ruff_cache",
    "venv",
    "__init__.py",
    ".db",
    ".db_dev",
    '.minio_data',
    ".minio_data_dev",
    ".idea",
]
target-version = "py311"
line-length = 79
indent-width = 4

[lint]
select = ["E", "F", "W", "C90"]
fixable = ["ALL"]

[format]
indent-style = "space"
quote-style = "single"
docstring-code-format = true
