version: '3.9'

name: "mad_soft_test_dev"

services:
  migrations:
    build:
      context: ../public_api
      dockerfile: ../public_api/migrations/Dockerfile
    env_file:
      - ../public_api/.env
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data_dev:/data
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://127.0.0.1:9000/minio/health/live' ]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  minio_data_dev:
  postgres_data_dev:
