version: '3.9'

name: "mad_soft_test_dev"

services:
  db:
    image: postgres:15.0-alpine
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ../.db_dev:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - ../.minio_data_dev:/data
