version: '3.9'

name: "mad_soft_test"

services:
  public_api:
    build: ../public_api
    restart: always
    env_file:
      - ../public_api/.env
    ports:
      - "${PUBLIC_API_PORT}:8000"
    depends_on:
      migrations:
        condition: service_started
      private_api:
        condition: service_started
      postgres_db:
        condition: service_healthy
    networks:
      - mad_soft

  private_api:
    build: ../private_api
    restart: always
    env_file:
      - ../private_api/.env
    ports:
      - "${PRIVATE_API_PORT}:8000"
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - mad_soft

  migrations:
    build:
      context: ../public_api
      dockerfile: ../public_api/migrations/Dockerfile
    env_file:
      - ../public_api/.env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - mad_soft

  postgres_db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - mad_soft

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://127.0.0.1:9000/minio/health/live' ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - mad_soft

volumes:
  minio_data:
  postgres_data:

networks:
  mad_soft:
